# Redirects for renamed files: legacy-search/busqueda-legada/busca-legada → vtex-search-legacy/vtex-search-legado

# English files
[[redirects]]
force = true
from = "/docs/en/faq/marketing-and-merchandising/why-legacy-search-engine-ignores-some-terms"
status = 308
to = "/docs/en/faq/marketing-and-merchandising/why-vtex-search-legacy-engine-ignores-some-terms"

[[redirects]]
force = true
from = "/docs/en/tutorials/catalog/search/how-does-legacy-search-work"
status = 308
to = "/docs/en/tutorials/catalog/search/how-does-vtex-search-legacy-work"

# Spanish files
[[redirects]]
force = true
from = "/docs/es/faq/marketing-and-merchandising/por-que-la-busqueda-legada-ignora-algunos-terminos-buscados"
status = 308
to = "/docs/es/faq/marketing-and-merchandising/por-que-vtex-search-legado-ignora-algunos-terminos-buscados"

[[redirects]]
force = true
from = "/docs/es/tutorials/catalogo/búsqueda/como-funciona-la-busqueda-legada"
status = 308
to = "/docs/es/tutorials/catalogo/búsqueda/como-funciona-vtex-search-legado"

# Portuguese files
[[redirects]]
force = true
from = "/docs/pt/tutorials/catálogo/busca/como-funciona-a-busca-legada"
status = 308
to = "/docs/pt/tutorials/catálogo/busca/como-funciona-vtex-search-legado"

[[redirects]]
force = true
from = "/docs/pt/faq/marketing-and-merchandising/por-que-a-busca-legada-ignora-alguns-termos-buscados"
status = 308
to = "/docs/pt/faq/marketing-and-merchandising/por-que-vtex-search-legado-ignora-alguns-termos-buscados"
