name: Generate Changelog

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  generate-changelog:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull
        run: git pull
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          check-latest: true
      
      - name: Set Git identity
        run: |
          git config user.name "julia-rabello"
          git config user.email "julia.alexandre@vtex.com"
      
      - name: Initialize CHANGELOG (first run)
        if: ${{ hashFiles('CHANGELOG.md') == '' }}
        run: |
          npx conventional-changelog -p angular -r 0 -o CHANGELOG.md

      - name: Update CHANGELOG
        if: ${{ hashFiles('CHANGELOG.md') != '' }}
        run: |
          npx conventional-changelog -p angular -o CHANGELOG.md -s

      - name: Commit and push CHANGELOG
        run: |
          if ! git diff --quiet -- CHANGELOG.md; then
            git add CHANGELOG.md
            git commit -m "docs(changelog): update"
            git push origin main
          else
            echo "No changes in CHANGELOG.md to commit."
          fi
