name: Help Center Files Scraper

on:
  pull_request:
    branches:
      - scrapper-tests
    types: [closed]

jobs:
  scrape-files:
    runs-on: ubuntu-latest
    name: Scraper running
    steps:
      - uses: actions/checkout@v4
      - name: Get changed markdown files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          include_all_old_new_renamed_files: "true"
          files: |
            **.md
            **.mdx
          separator: ","
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Added:"
          echo "${{ steps.changed-files.outputs.added_files }}"
          echo "Deleted:"
          echo "${{ steps.changed-files.outputs.deleted_files }}"
          echo "Modified:"
          echo "${{ steps.changed-files.outputs.modified_files }}"
          echo "Renamed:"
          echo "${{ steps.changed-files.outputs.all_old_new_renamed_files }}"
      - uses: actions/checkout@v2
      - name: Helpcenter Scraper
        uses: vtexdocs/devportal-docsearch-action@PedroAntunesCosta-spider-1
        with:
          algolia_application_id: '${{ secrets.ALGOLIA_APP_ID }}'
          algolia_api_key: ${{ secrets.ALGOLIA_WRITE_KEY }}
          files: './configs/scraper_helpcenter_files.json'
          added: '${{ steps.changed-files.outputs.added_files }}'
          updated: '${{ steps.changed-files.outputs.modified_files }}'
          removed: '${{ steps.changed-files.outputs.deleted_files }}'
          renamed: '${{ steps.changed-files.outputs.all_old_new_renamed_files }}'
