name: Index changed docs to Algolia

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**/*.md'
  pull_request:
    paths:
      - 'docs/**/*.md'
  workflow_dispatch:
    inputs:
      file:
        description: 'Optional markdown file path to index (e.g., docs/en/path/to/file.md)'
        required: false
        type: string

jobs:
  index-docs:
    name: Index changed markdown files
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    env:
      # Algolia configuration (set these in repository Secrets)
      NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      # Help Center hostname used to construct record URLs (optional override via repo Variables)
      HELP_CENTER_HOSTNAME: ${{ vars.HELP_CENTER_HOSTNAME || 'newhelp.vtex.com' }}

      # GitHub API token to increase rate limits for content fetches
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Repository context that the analyzer API uses to fetch markdown files
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}

      # Analyzer repository location and branch
      ANALYZER_REPO_SLUG: vtexdocs/algolia-index-analyzer
      ANALYZER_REF: design/cli-indexer-proposal

    steps:
      - name: Checkout content repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: algolia-index-analyzer/package-lock.json

      - name: Checkout analyzer repo (design/cli-indexer-proposal)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ANALYZER_REPO_SLUG }}
          ref: ${{ env.ANALYZER_REF }}
          path: algolia-index-analyzer
          # If the analyzer repo is private, provide a PAT via secrets.ANALYZER_REPO_TOKEN
          token: ${{ secrets.ANALYZER_REPO_TOKEN }}

      - name: Install analyzer dependencies
        run: npm ci --no-audit --no-fund
        working-directory: algolia-index-analyzer


      - name: Ensure jq is installed
        run: |
          set -euo pipefail
          if command -v jq >/dev/null 2>&1; then
            echo "jq already installed"
          else
            if command -v apt-get >/dev/null 2>&1; then
              sudo apt-get update || apt-get update
              sudo apt-get install -y jq || apt-get install -y jq
            elif command -v apk >/dev/null 2>&1; then
              sudo apk add --no-cache jq || apk add --no-cache jq
            else
              echo "Package manager not found; please ensure jq is available" >&2
              exit 1
            fi
          fi

      - name: Compute changed files (docs/**/*.md)
        id: changed
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.file == '' }}
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_REF="${{ github.event.pull_request.base.ref }}"
            git fetch --no-tags --prune origin "$BASE_REF" --depth=1
            BASE="origin/$BASE_REF"
            HEAD="HEAD"
          else
            BASE="${{ github.event.before }}"
            HEAD="HEAD"
            if [ -z "$BASE" ]; then
              BASE_REF="main"
              git fetch --no-tags --prune origin "$BASE_REF" --depth=1
              BASE="origin/$BASE_REF"
            fi
          fi
          CHANGED=$(git --no-pager diff --name-status "$BASE" "$HEAD" -- 'docs/**/*.md' | awk '$1 != "D" {print $NF}' | jq -R -s -c 'split("\n")|map(select(length>0))')
          echo "files=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: No docs changed
        if: ${{ github.event_name != 'workflow_dispatch' && steps.changed.outputs.files == '[]' }}
        run: echo "No markdown files changed under docs/, skipping."

      - name: Build file matrix from manual input
        id: manual
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.file != '' }}
        run: |
          echo "files=[\"${{ inputs.file }}\"]" >> "$GITHUB_OUTPUT"

      - name: Index changed docs
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.file != '') || steps.changed.outputs.files != '[]' }}
        run: |
          set -euo pipefail
          FILES_JSON='${{ steps.manual.outputs.files || steps.changed.outputs.files }}'
          echo "Indexing files: $FILES_JSON"
          echo "$FILES_JSON" | jq -r '.[]' | while read -r file; do
            [ -z "$file" ] && continue
            lang="$(echo "$file" | awk -F/ '{print $2}')"
            echo "Indexing $file (language=$lang)"
            # Direct mode: run without starting Next.js server
            node scripts/cli-index.js \
              --direct \
              --file "$file" \
              --language "$lang" \
              --index-name "${ALGOLIA_INDEX_NAME}" \
              --owner "${OWNER}" \
              --repo "${REPO}" \
              --json
          done
        working-directory: algolia-index-analyzer
